spring:
  profiles:
    active:
    - dev
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  mvc:
    async:
      request-timeout: 300000    
  security:
    user:
      name: admin
      password: admin
      #JSON美化输出
  jackson:
    serialization:
      indent-output: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlite:${user.home}/doudouflow.db
    driver-class-name: org.sqlite.JDBC  
  web:
    resources:
      static-locations:
      - classpath:/static/
      - classpath:/public/
logging:
  level:
    org.springframework.boot: debug
    org.doubdou: debug
    
---    
# 开发环境
spring:
  profiles: dev   
  thymeleaf:
    cache: false